import { SoCItem } from 'components/widgets/soc-managed-list/types';

const vendor = 'Anyka';
export const anykaSOCs: SoCItem[] = [
  {
    vendor: vendor,
    group: 'AK3918EV300',
    model: 'AK3916EV300',
    address: '',
    stage: 'NEQ',
    bootloader: '',
    firmware: 'openipc.ak3916ev300-nor-lite.tgz',
    featured: false,
    core: null,
    ai: null,
    package: null,
    encoder: null,
    memory: null,
  },
  {
    vendor: vendor,
    group: '',
    model: 'AK3916EV301',
    address: '',
    stage: 'RND',
    bootloader: '',
    firmware: 'openipc.ak3918ev200-nor-lite.tgz',
    featured: false,
    core: null,
    ai: null,
    package: null,
    encoder: null,
    memory: null,
  },
  {
    vendor: vendor,
    group: 'AK3918EV200',
    model: 'AK3918EV200',
    address: '0x81808000',
    stage: 'HLP',
    bootloader: '',
    firmware: '',
    featured: false,
    core: null,
    ai: null,
    package: null,
    encoder: null,
    memory: null,
  },
  {
    vendor: vendor,
    group: 'AK3918EV300',
    model: 'AK3918EV300',
    address: '',
    stage: 'NEQ',
    bootloader: '',
    firmware: 'openipc.ak3918ev300-nor-lite.tgz',
    featured: false,
    core: null,
    ai: null,
    package: null,
    encoder: null,
    memory: null,
  },
  {
    vendor: vendor,
    group: '',
    model: 'AK3918EV330',
    address: '',
    stage: 'RND',
    bootloader: '',
    firmware: '',
    featured: false,
    core: null,
    ai: null,
    package: null,
    encoder: null,
    memory: null,
  }
]
