import { SoCItem } from 'components/widgets/soc-managed-list/types';

const vendor = 'Fullhan';
export const fullhanSOCs: SoCItem[] = [
  {
    vendor: vendor,
    group: '',
    model: 'FH8626V100',
    address: '',
    stage: 'RND',
    bootloader: '',
    firmware: '',
    featured: false,
    core: null,
    ai: null,
    package: null,
    encoder: null,
    memory: null,
  },
  {
    vendor: vendor,
    group: '',
    model: 'FH8632V100',
    address: '',
    stage: 'NEQ',
    bootloader: '',
    firmware: '',
    featured: false,
    core: null,
    ai: null,
    package: null,
    encoder: null,
    memory: null,
  },
  {
    vendor: vendor,
    group: '',
    model: 'FH8652V100',
    address: '',
    stage: 'HLP',
    bootloader: '',
    firmware: '',
    featured: false,
    core: null,
    ai: null,
    package: null,
    encoder: null,
    memory: null,
  },
  {
    vendor: vendor,
    group: 'FH8852V100',
    model: 'FH8852V100',
    address: '',
    stage: 'WIP',
    bootloader: '',
    firmware: 'openipc.fh8852v100-nor-lite.tgz',
    featured: false,
    core: null,
    ai: null,
    package: null,
    encoder: null,
    memory: null,
  },
  {
    vendor: vendor,
    group: 'FH8852V200',
    model: 'FH8852V200',
    address: '0xA1000000',
    stage: 'WIP',
    bootloader: '',
    firmware: 'openipc.fh8852v200-nor-lite.tgz',
    featured: false,
    core: null,
    ai: null,
    package: null,
    encoder: null,
    memory: null,
  },
  {
    vendor: vendor,
    group: 'FH8852V200',
    model: 'FH8852V210',
    address: '',
    stage: 'NEQ',
    bootloader: '',
    firmware: '',
    featured: false,
    core: null,
    ai: null,
    package: null,
    encoder: null,
    memory: null,
  },
  {
    vendor: vendor,
    group: 'FH8852V100',
    model: 'FH8856V100',
    address: '',
    stage: 'NEQ',
    bootloader: '',
    firmware: '',
    featured: false,
    core: null,
    ai: null,
    package: null,
    encoder: null,
    memory: null,
  },
  {
    vendor: vendor,
    group: 'FH8852V200',
    model: 'FH8856V200',
    address: '',
    stage: 'WIP',
    bootloader: '',
    firmware: 'openipc.fh8856v200-nor-lite.tgz',
    featured: false,
    core: null,
    ai: null,
    package: null,
    encoder: null,
    memory: null,
  },
  {
    vendor: vendor,
    group: 'FH8852V200',
    model: 'FH8856V210',
    address: '',
    stage: 'NEQ',
    bootloader: '',
    firmware: '',
    featured: false,
    core: null,
    ai: null,
    package: null,
    encoder: null,
    memory: null,
  },
  {
    vendor: vendor,
    group: 'FH8852V200',
    model: 'FH8858V200',
    address: '',
    stage: 'NEQ',
    bootloader: '',
    firmware: '',
    featured: false,
    core: null,
    ai: null,
    package: null,
    encoder: null,
    memory: null,
  },
  {
    vendor: vendor,
    group: 'FH8852V200',
    model: 'FH8858V210',
    address: '',
    stage: 'NEQ',
    bootloader: '',
    firmware: '',
    featured: false,
    core: null,
    ai: null,
    package: null,
    encoder: null,
    memory: null,
  },
  {
    vendor: vendor,
    group: 'FH8833V100',
    model: 'FH8833V100',
    address: '',
    stage: 'NEQ',
    bootloader: '',
    firmware: '',
    featured: false,
    core: null,
    ai: null,
    package: null,
    encoder: null,
    memory: null,
  }
]
