import { SoCItem } from 'components/widgets/soc-managed-list/types';

const vendor = 'Goke';
export const gokeSOCs: SoCItem[] = [
  {
    vendor: vendor,
    group: 'GK710X',
    model: 'GK7102S',
    address: '0xC1000000',
    stage: 'HLP',
    bootloader: '',
    firmware: 'openipc.gk7102s-nor-lite.tgz',
    featured: false,
    core: null,
    ai: null,
    package: null,
    encoder: null,
    memory: null,
  },
  {
    vendor: vendor,
    group: 'GK7205V200',
    model: 'GK7202V300',
    address: '0x42000000',
    stage: 'DONE',
    bootloader: 'u-boot-gk7202v300-universal.bin',
    firmware: 'openipc.gk7202v300-nor-lite.tgz',
    featured: false,
    core: null,
    ai: null,
    package: null,
    encoder: null,
    memory: null,
  },
  {
    vendor: vendor,
    group: 'GK7205V200',
    model: 'GK7205V200',
    address: '0x42000000',
    stage: 'DONE',
    bootloader: 'u-boot-gk7205v200-universal.bin',
    firmware: 'openipc.gk7205v200-nor-lite.tgz',
    featured: true,
    core: null,
    ai: null,
    package: null,
    encoder: null,
    memory: null,
  },
  {
    vendor: vendor,
    group: 'GK7205V200',
    model: 'GK7205V210',
    address: '0x42000000',
    stage: 'DONE',
    bootloader: 'u-boot-gk7205v200-universal.bin',
    firmware: 'openipc.gk7205v210-nor-lite.tgz',
    featured: true,
    core: null,
    ai: null,
    package: null,
    encoder: null,
    memory: null,
  },
  {
    vendor: vendor,
    group: 'GK7205V200',
    model: 'GK7205V300',
    address: '0x42000000',
    stage: 'DONE',
    bootloader: 'u-boot-gk7205v300-universal.bin',
    firmware: 'openipc.gk7205v300-nor-lite.tgz',
    featured: true,
    core: null,
    ai: null,
    package: null,
    encoder: null,
    memory: null,
  },
  {
    vendor: vendor,
    group: 'GK7205V200',
    model: 'GK7605V100',
    address: '0x42000000',
    stage: 'DONE',
    bootloader: 'u-boot-gk7605v100-universal.bin',
    firmware: 'openipc.gk7605v100-nor-lite.tgz',
    featured: false,
    core: null,
    ai: null,
    package: null,
    encoder: null,
    memory: null,
  },
  {
    vendor: vendor,
    group: 'GK710X',
    model: 'GK7102CA',
    address: '0xC1000000',
    stage: 'HLP',
    bootloader: '',
    firmware: 'openipc.gk7102-nor-lite.tgz',
    featured: false,
    core: null,
    ai: null,
    package: null,
    encoder: null,
    memory: null,
  },
  {
    vendor: vendor,
    group: 'GK710X',
    model: 'GK7102CT',
    address: '0xC1000000',
    stage: 'NEQ',
    bootloader: '',
    firmware: 'openipc.gk7102-nor-lite.tgz',
    featured: false,
    core: null,
    ai: null,
    package: null,
    encoder: null,
    memory: null,
  },
  {
    vendor: vendor,
    group: 'GK710X',
    model: 'GK7102CW',
    address: '0xC1000000',
    stage: 'NEQ',
    bootloader: '',
    firmware: 'openipc.gk7102-nor-lite.tgz',
    featured: false,
    core: null,
    ai: null,
    package: null,
    encoder: null,
    memory: null,
  },
  {
    vendor: vendor,
    group: 'GK710X',
    model: 'GK7102C',
    address: '0xC1000000',
    stage: 'HLP',
    bootloader: '',
    firmware: 'openipc.gk7102-nor-lite.tgz',
    featured: false,
    core: null,
    ai: null,
    package: null,
    encoder: null,
    memory: null,
  },
  {
    vendor: vendor,
    group: 'GK7201V200',
    model: 'GK7201V200',
    address: '',
    stage: 'NEQ',
    bootloader: '',
    firmware: '',
    featured: false,
    core: null,
    ai: null,
    package: null,
    encoder: null,
    memory: null,
  },
  {
    vendor: vendor,
    group: 'GK7201V200',
    model: 'GK7201V300',
    address: '',
    stage: 'NEQ',
    bootloader: '',
    firmware: '',
    featured: false,
    core: null,
    ai: null,
    package: null,
    encoder: null,
    memory: null,
  },
  {
    vendor: 'Goke',
    group: 'GK710X',
    model: 'GK7102',
    address: '0xC1000000',
    stage: 'HLP',
    bootloader: '',
    firmware: 'openipc.gk7102-nor-lite.tgz',
    featured: false,
    core: null,
    ai: null,
    package: null,
    encoder: null,
    memory: null,
  },
]
