import { SoCItem } from 'components/widgets/soc-managed-list/types';

const vendor = 'Ingenic';
export const ingenicSOCs: SoCItem[] = [
  {
    vendor: vendor,
    group: 'T21',
    model: 'T10',
    address: '0x80600000',
    stage: 'DONE',
    bootloader: 'u-boot-t10-nor.bin',
    firmware: 'openipc.t10-nor-lite.tgz',
    featured: false,
    core: null,
    ai: null,
    package: null,
    encoder: null,
    memory: null,
  },
  {
    vendor: vendor,
    group: 'T21',
    model: 'T20',
    address: '0x80600000',
    stage: 'DONE',
    bootloader: 'u-boot-t20-nor.bin',
    firmware: 'openipc.t20-nor-lite.tgz',
    featured: false,
    core: null,
    ai: null,
    package: null,
    encoder: null,
    memory: null,
  },
  {
    vendor: vendor,
    group: 'T21',
    model: 'T21',
    address: '0x80600000',
    stage: 'DONE',
    bootloader: 'u-boot-t21n-nor.bin',
    firmware: 'openipc.t21-nor-lite.tgz',
    featured: false,
    core: null,
    ai: null,
    package: null,
    encoder: null,
    memory: null,
  },
  {
    vendor: vendor,
    group: 'T31',
    model: 'T31AL',
    address: '0x80600000',
    stage: 'DONE',
    bootloader: 'u-boot-t31al-nor.bin',
    firmware: 'openipc.t31-nor-lite.tgz',
    featured: false,
    core: null,
    ai: null,
    package: null,
    encoder: null,
    memory: null,
  },
  {
    vendor: vendor,
    group: 'T31',
    model: 'T31A',
    address: '0x80600000',
    stage: 'MVP',
    bootloader: 'u-boot-t31a-nor.bin',
    firmware: 'openipc.t31-nor-lite.tgz',
    featured: false,
    core: null,
    ai: null,
    package: null,
    encoder: null,
    memory: null,
  },
  {
    vendor: vendor,
    group: 'T31',
    model: 'T31L',
    address: '0x80600000',
    stage: 'DONE',
    bootloader: 'u-boot-t31l-nor.bin',
    firmware: 'openipc.t31-nor-lite.tgz',
    featured: true,
    core: null,
    ai: null,
    package: null,
    encoder: null,
    memory: null,
  },
  {
    vendor: vendor,
    group: 'T31',
    model: 'T31N',
    address: '0x80600000',
    stage: 'DONE',
    bootloader: 'u-boot-t31n-nor.bin',
    firmware: 'openipc.t31-nor-lite.tgz',
    featured: true,
    core: null,
    ai: null,
    package: null,
    encoder: null,
    memory: null,
  },
  {
    vendor: vendor,
    group: 'T31',
    model: 'T31X',
    address: '0x80600000',
    stage: 'DONE',
    bootloader: 'u-boot-t31x-nor.bin',
    firmware: 'openipc.t31-nor-lite.tgz',
    featured: true,
    core: null,
    ai: null,
    package: null,
    encoder: null,
    memory: null,
  },
  {
    vendor: vendor,
    group: 'T40',
    model: 'T40A',
    address: '0x80600000',
    stage: 'MVP',
    bootloader: 'u-boot-t40a-universal.bin',
    firmware: 'openipc.t40-nor-lite.tgz',
    featured: false,
    core: null,
    ai: null,
    package: null,
    encoder: null,
    memory: null,
  },
  {
    vendor: vendor,
    group: 'T40',
    model: 'T40N',
    address: '0x80600000',
    stage: 'DONE',
    bootloader: 'u-boot-t40n-universal.bin',
    firmware: 'openipc.t40-nor-lite.tgz',
    featured: false,
    core: null,
    ai: null,
    package: null,
    encoder: null,
    memory: null,
  },
  {
    vendor: vendor,
    group: 'T40',
    model: 'T40XP',
    address: '0x80600000',
    stage: 'DONE',
    bootloader: 'u-boot-t40xp-universal.bin',
    firmware: 'openipc.t40-nor-lite.tgz',
    featured: false,
    core: null,
    ai: null,
    package: null,
    encoder: null,
    memory: null,
  },
  {
    vendor: vendor,
    group: 'T40',
    model: 'T40NN',
    address: '0x80600000',
    stage: 'RND',
    bootloader: 'u-boot-t40n-universal.bin',
    firmware: 'openipc.t40-nor-lite.tgz',
    featured: false,
    core: null,
    ai: null,
    package: null,
    encoder: null,
    memory: null,
  },
  {
    vendor: vendor,
    group: 'T41',
    model: 'T41LC',
    address: '0x80600000',
    stage: 'RND',
    bootloader: '',
    firmware: '',
    featured: false,
    core: null,
    ai: null,
    package: null,
    encoder: null,
    memory: null,
  },
  {
    vendor: vendor,
    group: 'T41',
    model: 'T41ZL',
    address: '0x80600000',
    stage: 'RND',
    bootloader: '',
    firmware: '',
    featured: false,
    core: null,
    ai: null,
    package: null,
    encoder: null,
    memory: null,
  },
  {
    vendor: vendor,
    group: 'T41',
    model: 'T41ZN',
    address: '0x80600000',
    stage: 'RND',
    bootloader: '',
    firmware: '',
    featured: false,
    core: null,
    ai: null,
    package: null,
    encoder: null,
    memory: null,
  },
  {
    vendor: vendor,
    group: 'T23',
    model: 'T23N',
    address: '0x80600000',
    stage: 'RND',
    bootloader: '',
    firmware: '',
    featured: false,
    core: null,
    ai: null,
    package: null,
    encoder: null,
    memory: null,
  },
  {
    vendor: vendor,
    group: 'T41',
    model: 'T41A',
    address: '0x80600000',
    stage: 'RND',
    bootloader: '',
    firmware: '',
    featured: false,
    core: null,
    ai: null,
    package: null,
    encoder: null,
    memory: null,
  },
  {
    vendor: vendor,
    group: 'T41',
    model: 'T41L',
    address: '0x80600000',
    stage: 'RND',
    bootloader: '',
    firmware: '',
    featured: false,
    core: null,
    ai: null,
    package: null,
    encoder: null,
    memory: null,
  },
  {
    vendor: vendor,
    group: 'T41',
    model: 'T41LQ',
    address: '0x80600000',
    stage: 'RND',
    bootloader: '',
    firmware: '',
    featured: false,
    core: null,
    ai: null,
    package: null,
    encoder: null,
    memory: null,
  },
  {
    vendor: vendor,
    group: 'T41',
    model: 'T41N',
    address: '0x80600000',
    stage: 'RND',
    bootloader: '',
    firmware: '',
    featured: false,
    core: null,
    ai: null,
    package: null,
    encoder: null,
    memory: null,
  },
  {
    vendor: vendor,
    group: 'T41',
    model: 'T41NQ',
    address: '0x80600000',
    stage: 'RND',
    bootloader: '',
    firmware: '',
    featured: false,
    core: null,
    ai: null,
    package: null,
    encoder: null,
    memory: null,
  },
  {
    vendor: vendor,
    group: 'T41',
    model: 'T41XQ',
    address: '0x80600000',
    stage: 'RND',
    bootloader: '',
    firmware: '',
    featured: false,
    core: null,
    ai: null,
    package: null,
    encoder: null,
    memory: null,
  },
  {
    vendor: vendor,
    group: 'T41',
    model: 'T41ZX',
    address: '0x80600000',
    stage: 'RND',
    bootloader: '',
    firmware: '',
    featured: false,
    core: null,
    ai: null,
    package: null,
    encoder: null,
    memory: null,
  },
  {
    vendor: vendor,
    group: 'T31',
    model: 'T31ZL',
    address: '0x80600000',
    stage: 'DONE',
    bootloader: 'u-boot-t31l-nor.bin',
    firmware: 'openipc.t31-nor-lite.tgz',
    featured: false,
    core: null,
    ai: null,
    package: null,
    encoder: null,
    memory: null,
  },
  {
    vendor: vendor,
    group: 'T31',
    model: 'T31ZX',
    address: '0x80600000',
    stage: 'DONE',
    bootloader: 'u-boot-t31x-nor.bin',
    firmware: 'openipc.t31-nor-lite.tgz',
    featured: false,
    core: null,
    ai: null,
    package: null,
    encoder: null,
    memory: null,
  },
  {
    vendor: vendor,
    group: 'T31',
    model: 'T31LC',
    address: '0x80600000',
    stage: 'MVP',
    bootloader: 'u-boot-t31lc-nor.bin',
    firmware: 'openipc.t31-nor-lite.tgz',
    featured: false,
    core: null,
    ai: null,
    package: null,
    encoder: null,
    memory: null,
  },
  {
    vendor: vendor,
    group: 'T30',
    model: 'T30L',
    address: '0x80600000',
    stage: 'MVP',
    bootloader: 'u-boot-t30l-nor.bin',
    firmware: 'openipc.t30-nor-lite.tgz',
    featured: false,
    core: null,
    ai: null,
    package: null,
    encoder: null,
    memory: null,
  },
]
