import { SoCItem } from 'components/widgets/soc-managed-list/types';

// Missing. Based on https://github.com/OpenIPC/ipctool/issues/21
// SSC325DE	1xA7	128MB	3M@30fps	QFN128
// const mercury6 = 'mercury6 (SSC35X) Tiramisu'
// SSC359G	2xA53	Extern	12M@25fps	BGA439
// const infinity7 = 'Infinity7 (?) Muffin';

// VendornNaming convention
//E = Package (QFN128)
//D = Dual memory (128MB)
//Q = Quad memory (256MB)
//G = External memory

const vendor = 'SigmaStar';

const single_core = '1xCortex-A7';
const dual_core = '2xCortex-A7';

const infinity5 = 'Infinity5 (SSC32X) Pretzel';
const infinity6 = 'Infinity6 (SSC32X) Macaron';
const infinity6b0 = 'Infinity6b0 (SSC33X) Ispahan';
const infinity6e = 'Infinity6e (SSC33X) Pudding';
const infinity6c = 'Infinity6c (SSC37X) Maruko';

export const sigmaStarSOCs: SoCItem[] = [
  {
    vendor: vendor,
    group: infinity6,
    model: 'SSC325',
    address: '0x21000000',
    stage: 'DONE',
    bootloader: 'u-boot-ssc325-nor.bin',
    firmware: 'openipc.ssc325-nor-lite.tgz',
    featured: false,
    core: null,
    ai: null,
    package: null,
    encoder: null,
    memory: null,
  },
  {
    vendor: vendor,
    group: infinity6b0,
    model: 'SSC335',
    address: '0x21000000',
    stage: 'DONE',
    bootloader: 'u-boot-ssc335-nor.bin',
    firmware: 'openipc.ssc335-nor-lite.tgz',
    featured: true,
    core: single_core,
    ai: 0,
    package: 'QFN88',
    encoder: '3M@30fps',
    memory: 64,
  },
  {
    vendor: vendor,
    group: infinity6b0,
    model: 'SSC335DE',
    address: '0x21000000',
    stage: 'DONE',
    bootloader: 'u-boot-ssc335de-nor.bin',
    firmware: 'openipc.ssc335de-nor-lite.tgz',
    featured: true,
    core: single_core,
    ai: null,
    package: 'QFN128',
    encoder: '3M@30fps',
    memory: 128,
  },
  {
    vendor: vendor,
    group: infinity6b0,
    model: 'SSC337',
    address: '0x21000000',
    stage: 'DONE',
    bootloader: 'u-boot-ssc337-nor.bin',
    firmware: 'openipc.ssc337-nor-lite.tgz',
    featured: true,
    core: single_core,
    ai: null,
    package: 'QFN88',
    encoder: '5M@20fps',
    memory: 64,
  },
  {
    vendor: vendor,
    group: infinity6b0,
    model: 'SSC337DE',
    address: '0x21000000',
    stage: 'DONE',
    bootloader: 'u-boot-ssc337de-nor.bin',
    firmware: 'openipc.ssc337de-nor-lite.tgz',
    featured: true,
    core: single_core,
    ai: null,
    package: 'QFN128',
    encoder: '5M@20fps',
    memory: 128,
  },
  {
    vendor: vendor,
    group: infinity6b0,
    model: 'SSC333',
    address: '0x21000000',
    stage: 'DONE',
    bootloader: 'u-boot-ssc333-nor.bin',
    firmware: 'openipc.ssc333-nor-lite.tgz',
    featured: false,
    core: single_core,
    ai: 0,
    package: 'QFN88',
    encoder: '1080p@30fps,3M@20fps',
    memory: 64,
  },
  {
    vendor: vendor,
    group: infinity6b0,
    model: 'SSC333DE',
    address: '0x21000000',
    stage: 'NEQ',
    bootloader: '',
    firmware: '',
    featured: false,
    core: single_core,
    ai: null,
    package: 'QFN128',
    encoder: '3M@20fps',
    memory: 128,
  },
  {
    vendor: vendor,
    group: infinity5,
    model: 'SSC326D',
    address: '0x21000000',
    stage: 'NEQ',
    bootloader: '',
    firmware: '',
    featured: false,
    core: single_core,
    ai: null,
    package: 'QFN128',
    encoder: '3M@30fps',
    memory: 128,
  },
  {
    vendor: vendor,
    group: infinity5,
    model: 'SSC328Q',
    address: '0x21000000',
    stage: 'NEQ',
    bootloader: '',
    firmware: '',
    featured: false,
    core: single_core,
    ai: null,
    package: 'QFN128',
    encoder: '8M@20fps',
    memory: 256,
  },
  {
    vendor: vendor,
    group: infinity5,
    model: 'SSC329Q',
    address: '0x21000000',
    stage: 'NEQ',
    bootloader: '',
    firmware: '',
    featured: false,
    core: single_core,
    ai: null,
    package: 'QFN128',
    encoder: '8M@30fps',
    memory: 256,
  },
  {
    vendor: vendor,
    group: infinity6,
    model: 'SSC323',
    address: '0x21000000',
    stage: 'NEQ',
    bootloader: '',
    firmware: '',
    featured: false,
    core: single_core,
    ai: null,
    package: 'QFN88',
    encoder: '3M@20fp',
    memory: 64,
  },
  {
    vendor: vendor,
    group: infinity6,
    model: 'SSC327',
    address: '0x21000000',
    stage: 'NEQ',
    bootloader: '',
    firmware: '',
    featured: false,
    core: single_core,
    ai: null,
    package: 'QFN88',
    encoder: '5M@20fps',
    memory: 64,
  },
  {
    vendor: vendor,
    group: infinity6,
    model: 'SSC325D',
    address: '0x21000000',
    stage: 'NEQ',
    bootloader: '',
    firmware: '',
    featured: false,
    core: single_core,
    ai: null,
    package: 'QFN88',
    encoder: '3M@30fps',
    memory: 128,
  },
  {
    vendor: vendor,
    group: infinity6,
    model: 'SSC327D',
    address: '0x21000000',
    stage: 'NEQ',
    bootloader: '',
    firmware: '',
    featured: false,
    core: single_core,
    ai: null,
    package: "QFN88",
    encoder: '5M@30fps',
    memory: 128,
  },
  {
    vendor: vendor,
    group: infinity6,
    model: 'SSC327DE',
    address: '0x21000000',
    stage: 'NEQ',
    bootloader: '',
    firmware: '',
    featured: false,
    core: single_core,
    ai: null,
    package: 'QFN128',
    encoder: '5M@20fps',
    memory: 128,
  },
  {
    vendor: vendor,
    group: infinity6,
    model: 'SSC327Q',
    address: '0x21000000',
    stage: 'NEQ',
    bootloader: '',
    firmware: '',
    featured: false,
    core: single_core,
    ai: null,
    package: 'QFN128',
    encoder: '5M@20fps',
    memory: 256,
  },
  {
    vendor: vendor,
    group: infinity6e,
    model: 'SSC336D',
    address: '0x21000000',
    stage: 'NEQ',
    bootloader: '',
    firmware: '',
    featured: false,
    core: dual_core,
    ai: 0.5,
    package: 'QFN128',
    encoder: '3M@30fps',
    memory: 128,
  },
  {
    vendor: vendor,
    group: infinity6e,
    model: 'SSC336Q',
    address: '0x21000000',
    stage: 'NEQ',
    bootloader: '',
    firmware: '',
    featured: false,
    core: dual_core,
    ai: 0.5,
    package: "QFN128",
    encoder: '3M@30fps',
    memory: 256,
  },
  {
    vendor: vendor,
    group: infinity6e,
    model: 'SSC30KD',
    address: '0x21000000',
    stage: 'DONE',
    bootloader: 'u-boot-ssc30kd-nor.bin',
    firmware: 'openipc.ssc30kd-nor-lite.tgz',
    featured: true,
    core: single_core,
    ai: null,
    package: 'QFN128',
    encoder: '5M@30fps',
    memory: 128,
  },
  {
    vendor: vendor,
    group: infinity6e,
    model: 'SSC338D',
    address: '0x21000000',
    stage: 'NEQ',
    bootloader: '',
    firmware: '',
    featured: false,
    core: dual_core,
    ai: null,
    package: 'QFN128',
    encoder: '8M@20fps',
    memory: 128,
  },
  {
    vendor: vendor,
    group: infinity6e,
    model: 'SSC338G',
    address: '0x21000000',
    stage: 'NEQ',
    bootloader: '',
    firmware: '',
    featured: false,
    core: dual_core,
    ai: 1,
    package: 'BGA307',
    encoder: '8M@20fps',
    memory: null,
  },
  {
    vendor: vendor,
    group: infinity6e,
    model: 'SSC339G',
    address: '0x21000000',
    stage: 'NEQ',
    bootloader: '',
    firmware: '',
    featured: false,
    core: dual_core,
    ai: 1,
    package: 'BGA307',
    encoder: '8M@30fps',
    memory: null,
  },
  {
    vendor: vendor,
    group: infinity6c,
    model: 'SSC377',
    address: '0x21000000',
    stage: 'NEQ',
    bootloader: '',
    firmware: '',
    featured: false,
    core: single_core,
    ai: null,
    package: 'QFN88',
    encoder: '5M@30fps',
    memory: 64,
  },
  {
    vendor: vendor,
    group: infinity6c,
    model: 'SSC377D',
    address: '0x21000000',
    stage: 'NEQ',
    bootloader: '',
    firmware: '',
    featured: false,
    core: single_core,
    ai: null,
    package: 'QFN88',
    encoder: '5M@30fps',
    memory: 128,
  },
  {
    vendor: vendor,
    group: infinity6c,
    model: 'SSC377DE',
    address: '0x21000000',
    stage: 'NEQ',
    bootloader: '',
    firmware: '',
    featured: false,
    core: single_core,
    ai: null,
    package: 'QFN128',
    encoder: '5M@30fps',
    memory: 128,
  },
  {
    vendor: vendor,
    group: infinity6c,
    model: 'SSC377QE',
    address: '0x21000000',
    stage: 'NEQ',
    bootloader: '',
    firmware: '',
    featured: false,
    core: single_core,
    ai: null,
    package: 'QFN128',
    encoder: '5M@30fps',
    memory: 256,
  },
  {
    vendor: vendor,
    group: infinity6c,
    model: 'SSC378DE',
    address: '0x21000000',
    stage: 'NEQ',
    bootloader: '',
    firmware: '',
    featured: false,
    core: single_core,
    ai: null,
    package: 'QFN128',
    encoder: '8M@25fps',
    memory: 128,
  },
  {
    vendor: vendor,
    group: infinity6c,
    model: 'SSC378QE',
    address: '0x21000000',
    stage: 'NEQ',
    bootloader: '',
    firmware: '',
    featured: false,
    core: single_core,
    ai: null,
    package: 'QFN128',
    encoder: '8M@25fps',
    memory: 256,
  },
  {
    vendor: vendor,
    group: infinity6e,
    model: 'SSC30KQ',
    address: '0x21000000',
    stage: 'DONE',
    bootloader: 'u-boot-ssc30kq-nor.bin',
    firmware: 'openipc.ssc30kq-nor-lite.tgz',
    featured: true,
    core: single_core,
    ai: null,
    package: 'QFN128',
    encoder: '5M@30fps',
    memory: 256,
  },
  {
    vendor: vendor,
    group: infinity6e,
    model: 'SSC338Q',
    address: '0x21000000',
    stage: 'DONE',
    bootloader: 'u-boot-ssc338q-nor.bin',
    firmware: 'openipc.ssc338q-nor-lite.tgz',
    featured: true,
    core: dual_core,
    ai: 0.5,
    package: 'QFN128',
    encoder: '4k@20fps,8M@20fps',
    memory: 256,
  },
];
