import { SoCItem } from 'components/widgets/soc-managed-list/types';

const vendor = 'Xiongmai';
export const xiongmaiSOCs: SoCItem[] = [
  {
    vendor: vendor,
    group: 'XM510',
    model: 'XM510',
    address: '0x80007FC0',
    stage: 'MVP',
    bootloader: '',
    firmware: 'openipc.xm510-nor-lite.tgz',
    featured: false,
    core: null,
    ai: null,
    package: null,
    encoder: null,
    memory: null,
  },
  {
    vendor: vendor,
    group: 'XM530',
    model: 'XM530',
    address: '0x81000000',
    stage: 'MVP',
    bootloader: '',
    firmware: 'openipc.xm530-nor-lite.tgz',
    featured: false,
    core: null,
    ai: null,
    package: null,
    encoder: null,
    memory: null,
  },
  {
    vendor: vendor,
    group: 'XM550',
    model: 'XM550',
    address: '0x81000000',
    stage: 'MVP',
    bootloader: '',
    firmware: 'openipc.xm550-nor-lite.tgz',
    featured: false,
    core: null,
    ai: null,
    package: null,
    encoder: null,
    memory: null,
  }
]
