import { SoCItem } from '../../../../../components/widgets/soc-managed-list/types';

export const socs: SoCItem[] = [
  {
    vendor: 'Allwinner',
    model: 'V831',
    address: null,
    stage: 'NEQ',
    installation: false,
    featured: false,
  },
  {
    vendor: 'Ambarella',
    model: 'S2L',
    address: null,
    stage: 'NEQ',
    installation: false,
    featured: true,
  },
  {
    vendor: 'Anyka',
    model: 'AK3918EV200',
    address: '0x81808000',
    stage: 'HLP',
    installation: false,
    featured: false,
  },
  {
    vendor: 'Fullhan',
    model: 'FH8852V200',
    address: '0xA1000000',
    stage: 'WIP',
    installation: false,
    featured: true,
  },
  {
    vendor: 'Goke',
    model: 'GK7202V300',
    address: '0x42000000',
    stage: 'DONE',
    installation: true,
    featured: false,
  },
  {
    vendor: 'GrainMedia',
    model: 'GM8136',
    address: '0x2000000',
    stage: 'MVP',
    installation: false,
    featured: true,
  },
  {
    vendor: 'HiSilicon',
    model: 'HI3516EV300',
    address: '0x42000000',
    stage: 'DONE',
    installation: true,
    featured: false,
  },
  {
    vendor: 'Ingenic',
    model: 'T40A',
    address: '0x80600000',
    stage: 'MVP',
    installation: true,
    featured: true,
  },
  {
    vendor: 'MStar',
    model: 'MSC313E',
    address: '0x21000000',
    stage: 'WIP',
    installation: true,
    featured: false,
  },
  {
    vendor: 'Novatek',
    model: 'NT98562',
    address: null,
    stage: 'WIP',
    installation: false,
    featured: true,
  },
  {
    vendor: 'Rockchip',
    model: 'RV1126',
    address: null,
    stage: 'RND',
    installation: false,
    featured: false,
  },
  {
    vendor: 'SigmaStar',
    model: 'SSC338Q',
    address: '0x21000000',
    stage: 'DONE',
    installation: true,
    featured: true,
  },
  {
    vendor: 'TI',
    model: 'DM365',
    address: null,
    stage: 'NEQ',
    installation: false,
    featured: false,
  },
  {
    vendor: 'Xiongmai',
    model: 'XM510',
    address: '0x80007FC0',
    stage: 'MVP',
    installation: false,
    featured: true,
  },
];
