name: test-deployment
run-name: Test deployment with GH Actions
on:
  push:
    branchs:
      - test-deploy
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.11'
      - name: Enable and set up Yarn
        run: |
          corepack enable
          yarn set version stable
      - name: Install packages and build
        run: |
          yarn install
          yarn run build-main
      - name: Get production artifact
        uses: actions/upload-artifact@v4
        with:
          name: production-build
          path: dist
  deploy:
    runs-on: ubuntu-latest
    env:
      SERVER_NAME: ${{ vars.SERVER_NAME }}
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Download production articfact
        uses: actions/download-artifact@v4
        with:
          name: production-build
      - name: Display artifact files
      - name: Prepare folders on production server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ vars.SERVER_NAME }}
          username: root
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script_path: ./scripts/copy2site.sh
      - name: Copy build to production server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ vars.SERVER_NAME }}
          username: root
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          source: main/*
          target: /var/www/webface_test
